### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by asundukov** [savinsergey/database#1]
1. форматирование. Длинные "портянки" полей при создании таблиц лучше все же в столбик выстраивать - они так читаются легче и четче.
2. автоинкрементные поля. Для таблиц в 99% случаев для ID-полей лучше использовать автоинкрементные поля - в таком случае при вставке данных несколькими клиентами одновременно им не нужно будет блочить таблицу, доставать последний айдишник и самостоятельно добавлять новый - бд это за них сделает - избежим блокировок и/или коллизий.
3. генерацию данных лучше начинать с независимых таблиц (без внешних ключей), а деле в таблицы с внешними ключами вставлять данные через генераторы + джоин уже заполненных таблиц + использование рандом функций. Таким образом у нас будут валидные данные при каждом запуске инсертов, при том что можно будет менять объемы таблиц, а сгенерированные данные останутся валидными.
4. user_id на компании выглядит немного алогично - у компании может быть несколько HR-ов. Лучше company_id вешать на таблицу user. еще лучше создать для таблицы user расширение в виде user_hr (аналогично для соискателя - user_applicant). В расширения можно добавить поля уникальные только для этих подролей. Тогда пользователи не будут пересекаться по ролям, а резюме будут привязаны к сущности соискателя, а не к сущости пользователя, у которого в общем случае может быть и компания с вакансиями.
5.  запрос 1. not in выгоднее заменить на LEFT JOIN vacancies v c дальнейшей проверкой WHERE v.id is null. Конечно в таком случае придется отказаться от синтаксиса `SELECT something FROM t1, t2, t3 WHERE ...`, т.к. он подразумевает только INNER JOIN'ы
6. запрос 3 - аналогично пункту 5.

в остальном ок

**Comment by savinsergey** [comment]
Исправил 1, 2, 5 и 6
